name: hive_cache
description: A persistent cache that uses hive.
version: 2.0.0
homepage: https://github.com/marcelgarus/hive_cache

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.14.0
  flutter_cached: ^5.0.0
  hive: ^1.2.0
  hive_flutter: ^0.3.0+2
  meta: ^1.1.8
  rxdart: ^0.23.1
